config/routes.rb
Demo::Application.routes.draw do

  

  get "sign_up" => "users#new", :as => "sign_up"
  get "log_in" => "sessions#new", :as => "log_in" 
  get "log_out" => "sessions#destroy", :as => "log_out" 

  resources :articles, :users, :sessions, :comments
  
  namespace :admin do
    resources :articles
  end
  
  root :to => "users#new"
 
  

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :id, :title, :content, :user_id
  belongs_to :user
  has_many :comments, :dependent => :destroy

  validates :title, :length => {:minimum => 3, :maximum => 50},
                    :presence => true,
                    :format => {:with => /[a-zA-Z\s]+$/},
                    :uniqueness => true
  
  validates :content, :presence => true,
                      :length => {:minimum => 5, :maximum => 255}
  
  validates :user_id, :presence => true,
                      :numericality => true
  
  validate :valid_title
  def valid_title
    self.errors[:title] << "don't same with label 'title'" if title == 'title'
  end

  scope :ardhi_articles, where("user_id = 1")
  #scope :Product.price_more_than_1000
  #scope :Article.rating_is_and_above(rating)

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::ApplicationController
  before_filter :require_admin_login
  def list
   end
   def show
     @article = Article.find(params[:id])
     @comment = Comment.new
     @comments = Comment.where("article_id = #{params[:id]}")
   end
   def new
     @article = Article.new
   end
   def create
     @article = Article.create(params[:article]) #[:title] tambahin disebelah [:article] supaya dapat mengambil satu per satu
     if @article.save
       flash[:notice] = 'Success save into database'
       redirect_to articles_path
         else
           flash[:error] = 'Not Success please try again'
           render :action => :new
         end
   end
   def edit
    @article = Article.find(params[:id])
   end
   def update
    @article = Article.find(params[:id])
    if @article.update_attributes(params[:article])
      flash[:notice] = 'Success update and save into database'
      redirect_to articles_path
        else
          flash[:error] = 'Not Success to update please try again'
          render :action => :edit
        end
   end
   def destroy
     @article = Article.find(params[:id])
     @article.destroy
     flash[:notice] = 'Success delete from database'
     redirect_to articles_path
   end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
before_filter :require_login, :only => [:new, :create, :edit, :update, :delete]
   def list
   end
   def show
     @article = Article.find(params[:id])
     @comment = Comment.new
     @comments = Comment.where("article_id = #{params[:id]}")
   end
   def new
     @article = Article.new
   end
   def create
     @article = Article.create(params[:article]) #[:title] tambahin disebelah [:article] supaya dapat mengambil satu per satu
     if @article.save
       flash[:notice] = 'Success save into database'
       redirect_to articles_path
         else
           flash[:error] = 'Not Success please try again'
           render :action => :new
         end
   end
   def edit
    @article = Article.find(params[:id])
   end
   def update
    @article = Article.find(params[:id])
    if @article.update_attributes(params[:article])
      flash[:notice] = 'Success update and save into database'
      redirect_to articles_path
        else
          flash[:error] = 'Not Success to update please try again'
          render :action => :edit
        end
   end
   def destroy
     @article = Article.find(params[:id])
     @article.destroy
     flash[:notice] = 'Success delete from database'
     redirect_to articles_path
   end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  #def delete
  #link_to "Delete", {:controller => "articles", :action => "delete"}
  #end
end

app/views/articles/_comments.html.erb
<h2>Comments</h2>
<% @comments.each do |comment| %>
  Name: <%= comment.commenter %><br />
  Comment: <%= comment.body %><br /><br />
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Form</h1>
<%= flash[:error] %>
<% if @article.errors.any? %>
    <% @article.errors.full_messages.each do |message| %>
        <li class="cf-messages-li"><%= message %></li>
    <% end %>
<% end %>
<%= form_for @article do |a| %>
  <table>	
    <tr>
      <td><%= a.label :title %></td>
      <td>:</td>
      <td><%= a.text_field :title %></td>
    </tr>
    <tr>
      <td><%= a.label :content %></td>
      <td>:</td>
      <td><%= a.text_area :content %></td>
    </tr>
    <tr>
      <td><%= a.label :user_id, "User_id" %></td>
      <td>:</td>
      <td><%= a.text_field :user_id %></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td><%= a.submit %></td>
    </tr>
  </table>
<% end %>

app/views/articles/index.html.erb
<h1>List Articles</h1>
<%= flash[:notice] %>
<%= flash[:error] %>
  <table>
    <tr>
      <td>Id Article</td>
      <td>Title</td>
      <td>User_id</td>
      <td>Action</td>
    </tr>
      <% @article = Article.all %>
      <% @article.each do |temp|%>
        <tr>     
          <td><%= temp.id %></td>
          <td><%= temp.title %></td>
          <td><%= temp.user_id %></td>
          <td>
            <%= link_to "Edit", edit_article_path(temp.id) %>
          </td>
          <td>
            <%= link_to "Show", article_path(temp.id), :method => :get %>
          </td>
          <td>
            <%= link_to "Delete", article_path(temp.id), :method => :delete %>
          </td>
        </tr>
      <% end %>
  </table>
<%= link_to "Make new", new_article_path %>

app/views/articles/new.html.erb
<h1>New Articles</h1>
<%= flash[:error] %>
<% if @article.errors.any? %>
    <% for message in @article.errors.full_messages %>
        <li><%= message %></li>
    <% end %>
<% end %>
  <%= form_for @article do |a| %>
  <table>
    <tr>
      <td><%= a.label :title %></td>
      <td>:</td>
      <td><%= a.text_field :title %></td>
    </tr>
    <tr>
      <td><%= a.label :content %></td>
      <td>:</td>
      <td><%= a.text_area :content %></td>
    </tr>
    <tr>
      <td><%= a.label :user_id, "User_id"%></td>
      <td>:</td>
      <td><%= a.text_field :user_id %></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td><%= a.submit %></td>
    </tr>
  </table>
<% end %>

app/views/articles/show.html.erb
<!--<h1><%= @article.title %></h1>
<p><%= @article.content %></p>-->

<p id="notice"><%= notice %></p>
 
<p>
  <b>id:</b>
  <%= @article.id %>
</p>
 
<p>
  <b>Title:</b>
  <%= @article.title %>
</p>
 
<p>
  <b>Content:</b>
  <%= @article.content %>
</p>
 
<h2>Comments</h2>
<div id="comments">
  <%= render :partial => "comments", :locals => {:comments => @comments}  %>
</div><br />
 
<h2>Add a comment:</h2>
<%= form_for @comment, :url => comments_path, :remote => true do |f| %>
    <%= f.hidden_field :article_id, :value => @article.id %><br />
  <div class="field">
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Edit Post', edit_article_path(@article) %> |
<%= link_to 'Back to Article', articles_path %>